### ISSUE TITLE
Allow booleans for functions that take a single argument

### ISSUE THREAD

**Issue by achrinza** [foxglove/eslint-config#30]
Functions that accept a single argument should not need to accept an object to accept boolean values since:

- Their argument signature is simple
- Other single-argument functions that do not accept booleans are not affected by this rule (i.e. Why should boolean be the outlier?)

**Affected ESLint plugin:** [@foxglove/no-boolean-parameters](https://github.com/foxglove/eslint-plugin/blob/2cb07e26fead7dfc815ae06c5e0ef033085a5bdc/rules/no-boolean-parameters.js)

**Sample code snippets:**

- https://github.com/loopbackio/loopback-next/blob/87cfbea1d9457f72cdb621330a1afe8c05a4bcc4/packages/openapi-v3/src/decorators/deprecated.decorator.ts#L53
- https://github.com/loopbackio/loopback-next/blob/87cfbea1d9457f72cdb621330a1afe8c05a4bcc4/packages/repository/src/types/boolean.ts#L32
- https://github.com/loopbackio/loopback-next/blob/87cfbea1d9457f72cdb621330a1afe8c05a4bcc4/packages/repository/src/types/null.ts#L32

**Comment by defunctzombie** [comment]
Functions that accept single boolean arguments can also fall into the boolean trap (as indicated in the PR description here https://github.com/foxglove/eslint-plugin/pull/29). The first example with the deprecated decorator could be seen as a boolean trap as it is ambiguous to what the boolean value indicates (ie. reading `@deprecated(false)` makes me wonder what the false means since if I didn't want to mark something deprecated I'd just omit the decorator altogether). The blog post linked in the PR 29 is an insightful overview on the thoughts around such apis and how they impact readability.

I agree that the other two examples are false positives and make sense in the context of the apis they are implementing. Our reasoning was that it would be easy to add eslint ignore statements around such cases when they do come up and that the benefit of the rule would outweigh such things. If in practice we find that not true we will look at revising the rule.

@jtbandes might have some additional thoughts or approaches we could try for the two false positive cases described.

**Comment by jtbandes** [comment]
I do agree that single-arg functions `setX(val)` and 2-arg setters `set(key, val)` seem to be the most common “false positives” produced by this rule, i.e. the warnings most likely to be suppressed. Depending how opinionated we want to be with this rule, I think it could make sense to make this an **optional** (I’d argue for off by default) configuration flag, like `[error, {allowLoneParameters: true}]`.

An alternative way of dealing with this as outlined in a follow-up blog post (https://ariya.io/2012/06/detecting-boolean-traps-with-esprima.html) is to allow functions whose names start with `set-` (or more generally to allow the user to configure a regex to match allowed function names). This might get closer to the root cause of the false positive: certain classes of APIs where the function name provides enough context for the argument to be understood at the call site. What do you think?

By the way, why does NullType accept a boolean value for serialize()? 😅

**Comment by jtbandes** [comment]
Posted #33 which should solve this issue. Let me know what you think!

To address another point:

> Other single-argument functions that do not accept booleans are not affected by this rule (i.e. Why should boolean be the outlier?)

We were also thinking about extending this rule to other primitive types! `draw(0)` isn't much clearer than `draw(true)` 😅
